export default {
    email_placeholder :"Email",
    password_placeholder:"Contraseña",
    login_button:"Iniciar Sesión",
    register_link:"Registrarse",
    forgot_password_link:"Olvidaste tu contraseña?",
    facebook_login_button:'Facebook Login.',
    password_blank_messege:'La contraseña no puede estar vacía.',
    password_alphaNumeric_check:'La contraseña debe tener al menos 1 carácter alfanumérico y una longitud de 8 a 15.',
    password_complexity_check:'La contraseña debe tener al menos 1 letra minúscula, 1 letra mayúscula, 1 dígito, 1 carácter especial y una longitud de 6 a 10.',
    valid_email_check:'Por favor, introduce una dirección de correo electrónico válida.',
    facebook_login_error:'Ya tienes una cuenta con esta dirección de correo electrónico. Inicie sesión con su correo electrónico y contraseña.',
    forgot_password_success_messege:'El enlace de restablecimiento de contraseña enviado a su correo electrónico, verifique y restablezca su nueva contraseña.',
    facebook_login_auth_error:'Facebook Login Error:',
    static_notification_title:'Notificación Uder',
    refferal_code_validation_modal:'Validación de su código de referencia...',
    refferal_id_not_match_error:'Esta no es una identificación de referencia válida.',
    registration_title:'Registro de Usuario',
    first_name_placeholder:'Nombre(s)',
    first_name_blank_error:"Por favor, introduzca su nombre.",
    last_name_placeholder:'Apellidos',
    last_name_blank_error:'Por favor ingrese sus apellidos.',
    mobile_no_placeholder:'Número de Teléfono',
    mobile_no_blank_error:'Por favor, introduzca un número de móvil válido.',
    confrim_password_placeholder:'Confirmar Contraseña',
    confrim_password_not_match_err:'Las contraseñas no coinciden',
    referral_id_placeholder:'ID de referido (opcional)',
    register_button:'Registrarse ahora!',
    email_exist_error:'La dirección de correo electrónico ya está siendo utilizada por otra cuenta.',
    Account_linking_error:'Error de vinculación de cuenta',
    send_email_button:'Enviar correo electrónico',
    book_your_ride_menu:'Reserve su viaje',
    profile_setting_menu:'Perfil',
    my_wallet_menu:'Mi billetera',
    my_rides_menu:'Mis viajes',
    about_us_menu:'Quienes somos?',
    logout:'Cerrar sesión',
    photo_upload_action_sheet_title:'¿Elija una fotografía?',
    camera:'Cámara',
    galery:'Galería',
    cancel:'Cancelar',
    yes:'Si',
    network_request_failed:'Error en la solicitud de red',
    password_update_messege:'Tu contraseña se actualizó correctamente',
    delete_account_modal_title:'Esta acción eliminará tu cuenta',
    delete_account_modal_subtitle:'¿Quieres eliminar tu cuenta?',
    profile_page_title:'Mi perfil',
    my_wallet_title:'Mi saldo de Billetera',
    profile_page_subtitle:'Detalles del perfil',
    location_lebel:'Ubicación',
    language_lebel:'Lenguaje',
    preffer_language:'Español',
    change_password_lebel:'Cambiar contraseña',
    delete_account_lebel:'Eliminar cuenta',
    change_password_modal_title:'¿Cambiar la contraseña?',
    old_password_placeholder:'Contraseña anterior',
    new_password_placeholder:'Nueva contraseña',
    old_password_validation_error:'Ingrese una contraseña anterior',
    new_password_validation_error:'Ingrese una nueva contraseña',
    update_button:'Actualizar ahora',
    update_profile_title:'Actualización del perfil',
    map_screen_where_input_text:'De donde?',
    map_screen_drop_input_text:'A donde vas?',
    driver_finding_alert:'Buscando conductor disponible',
    no_driver_found_alert_title:'¡Alerta!',
    no_driver_found_alert_messege:'Lo sentimos, no se encontraron conductores en este momento. Vuelva a intentarlo más tarde.',
    no_driver_found_alert_OK_button:'OK',
    no_driver_found_alert_TRY_AGAIN_button:'Inténtalo de nuevo',
    pickup_and_drop_location_blank_error:'Seleccione la ubicación de recogida y entrega',
    pickup_location_blank_error:'Seleccionar lugar de recogida',
    drop_location_blank_error:'Seleccionar ubicación de destino',
    car_type_blank_error:'Seleccionar tipo de Servicio',
    congratulation:'Felicidades!',
    refferal_bonus_messege_text:'Monto de su bonificación por recomendación -',
    map_screen_title:'Uder Taxi App',
    cab_selection_title:'Elija su Localidad',
    cab_selection_subtitle:'Toca para seleccionar el de servicio y Solicite su Viaje',
    not_available:'No disponible', 
    book_now_button:'Solicitar Viaje',
    contact_details:'Detalles de contacto',
    phone:'Teléfono',
    my_wallet_tile:'Mi billetera',
    wallet_ballance:'Balance de Billetera',
    add_money:'Agregar dinero',
    transaction_history_title:'Historial de transacciones de billetera',
    successfully:'Exitosamente',
    form_wallet:'Billetera',
    Transaction_Id :'ID de Transacciones ',
    ride_list_title:'Mis Viajes',
    no_car_assign_text:'No hay Servicio asignado',
    not_found_text:'No encontrado',
    ride_details_page_title:'Detalles de mis viajes',
    you_rated_text:'Tus Calificaciones',
    car_no_not_found:'Número de auto no encontrado',
    track_now_button:'Seguimiento ahora',
    bill_details_title:'Detalles de la factura',
    your_trip:'Tu viaje',
    discount:'Descuento',
    promo_apply:'(Aplicar promoción)',
    grand_total:'Total',
    payment_status:'Status del pago',
    paynow_button:'Pagar ahora',
    call_driver:'Llamar al conductor',
    booked_cab_title:'Servicio reservado',
    you_selected:'Seleccionaste -',
    otp:'OTP :',
    driver_assign_messege:'El conductor se asignará pronto ...',
    cancel_ride:'Cancelar viaje',
    rider_cancel_text:'Cancelar viaje',
    cancel_messege1:'Tu viaje con ID de reserva',
    cancel_messege2:'Ha sido cancelado con éxito',
    dont_cancel_text:'No cancelar',
    cancel_reason_modal_title:'¿Cuál es el motivo para cancelar?',
    chat_title:'Chat',
    send_button_text:'Enviar',
    chat_input_title:'Escribe aquí tu mensaje ...',
    chat_not_found:'No se encontró historial de chat',
    card_payment_blank_error:'Por favor complete todos los detalles correctamente.',
    payment_amound_error:'El monto del pago es insuficiente.',
    invalid_card_details_error:'La tarjeta no es válida.',
    success_payment:'Pago exitoso',
    confrimation:'Confirmación',
    payment_alert:'¿Quieres eliminar tu tarjeta?',
    please_wait:'Por favor espere...',
    enterCVV:'Por favor introduzca CVV',
    your_promo:'Tu promoción',
    promo_exp:'Lo sentimos!\nEl código promocional y el límite de uso de la promoción expiraron.',
    promo_limit:'Lo sentimos!\nSe superó el límite de uso de la promoción.',
    promo_eligiblity:'Lo sentimos!\nNo eres elegible para esta promoción.',
    payment:'Pago',
    bill_details:'Detalles de la factura',
    apply_promo:'Aplicar promoción',
    your_fare:'Tu tarifa',
    promo_discount:'Descuento promocional',
    wallet_discount:'Descuento de billetera',
    payable_ammount:'Cantidad a pagar',
    use_wallet_balance:'Usar Billetera (Tu balance - ',
    pay_cash:'Pagar en efectivo',
    pay_card:'Pagar con tarjeta',
    proceed_pay:'Proceda a pagar',
    save_card:'Tus tarjetas guardadas',
    thanks:'Gracias por calificar',
    skip:'Omitir',
    receipt:'Recibo',
    rate_ride:'POR FAVOR CALIFICA TU VIAJE',
    err:'Error!',
    route_not_found:'No se pudo encontrar ninguna ruta',
    sorry:'Lo sentimos!',
    multipleBooking:'Uder actualmente no admite reservas múltiples.',
    driver_not_found:'No podemos asignar conductor en este momento. contacte con el administrador !!',
    new_booking_request_push_notification:'Tiene una nueva solicitud de reserva',
    fare_details:'Detalle de tarifa',
    base_fare:'Tarifa base',
    convenience_free:'Tarifa de Servicio',
    total_fare:'Tarifa total',
    inclusive_tax:'(Incluidos todos los impuestos)',
    nb:'NOTA: Su tarifa aumentará si el peaje, la ruta y el destino cambian o si el viaje tomó más tiempo debido al tráfico u otros',
    confrim_booking:'Aceptar y Viajar',
    estimate_fare_text:'Esta es solo su tarifa estimada',
    done:'Hecho',
    notification_headerText:'Notificación',
    notification_not_found:'No se encontró ninguna notificación',
    track_cab:'Seguimiento de su Servicio',
    location_permission:'Permiso de acceso a la ubicación',
    ask_me_later:'Pregúntame Luego',
    min_order_value:'Valor mínimo de pedido-',
    add_money_tile:'Agregar Saldo',
    addMoneyTextInputPlaceholder:'Agregar cantidad ($)',
    transactionFaildMsg:'Transacción fallida',
    payWithCard:'Pagar con tarjeta',
    CardPaymentAmount:'Pagar con tarjeta',
    CashPaymentAmount:'Pagar en efectivo',
    WalletPayment:'Pagar con billetera',
    pay_mode:'Modo de pago',
    Balance:'Balance Uder',
    android_channel: 'Notificaciones Uder'
}
